name: flutter_automation
description: A flutter package that provides various automation scripts to help you with your flutter project.
version: 1.2.0
author: Damodar Lohani<dlohani48@gmail.com>
homepage: https://github.com/lohanidamodar/flutter_automation

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  args: ^1.5.2
  yaml: ^2.1.16
  path: ^1.6.2

dev_dependencies:
  flutter_test:
    sdk: flutter